# Site settings
title: AtomLinter
url: https://atomlinter.github.io
description: Lint your code with ease in Atom.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: efeae1
  secondary: 66595c
  active: 81c08b

# Footer settings
footer:
  copyright: 2015 Kepler Sticka-Jones

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - LICENCE
  - README.md
